---
- gather_facts: off
  hosts: cisco1:cisco2
  tasks:
    - ios_command:
        commands: show lldp neighbors
      register: lldp_out
    
#    - debug:
#        msg: "{{ lldp_out }}"
#        msg: "{{ lldp_out['stdout_lines'][0] }}"

    - set_fact:
        lldp_entry: "{{ item }}"
      loop: "{{ lldp_out['stdout_lines'][0] }}"
      when: "'twb-sf-hpsw1' in item"
        
    - set_fact:
        remote_device: "{{ lldp_entry.split()[0] }}"
        local_intf: "{{ lldp_entry.split()[1] }}"
        remote_intf: "{{ lldp_entry.split()[4] }}"

    - debug:
        msg:
          - "Remote device: {{ remote_device }}"
          - "Local intf: {{ local_intf }}"
          - "Remote intf: {{ remote_intf }}"

